In [20]:
import cv2
import numpy as np

In [2]:
'''
Siempre se debe umbralizar

CHAIN_APROX se utiliza cuando hay puntos redundantes en la figura

'''
image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\image.png")
image_GRAY = cv2.cvtColor(image_BGR,cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

ret, image_with_threshold = cv2.threshold(image_GRAY, valor_umbral, valor_maximo, tipo)
contours, hierarchy = cv2.findContours(image_with_threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
#print(contours)
color = (0,255,0)
cv2.drawContours(image_BGR,contours,-1, color,8)
cv2.imshow("imagen umbralizada", image_with_threshold)
cv2.imshow("imagen con contornos", image_BGR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

### Contornos en video de objetos de color rojo

In [4]:
import cv2
import numpy as np 

cap = cv2.VideoCapture("C:\\Jupyter\\pdi\\imagenes\\circles.avi")

Redlower1 = np.array([0,80,80], np.uint8)
Redupper1 = np.array([8,255,255], np.uint8)

Redlower2 = np.array([175,80,80], np.uint8)
Redupper2 = np.array([179,255,255], np.uint8)

while cap.isOpened():
	ret, frame = cap.read()
	frame_hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
	mascara1 = cv2.inRange(frame_hsv, Redlower1, Redupper1)
	mascara2 = cv2.inRange(frame_hsv, Redlower2, Redupper2)
	mascara = cv2.add(mascara1, mascara2)
	contours, hierarchy = cv2.findContours(mascara,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
	color = (0,255,0)
	cv2.drawContours(frame,contours,-1,color,2)
	#filtro_img = cv2.bitwise_and(frame,frame,mask = mascara)
	if ret == True:
		cv2.imshow("Video", frame)
		#cv2.imshow("mascara",mascara)
		#cv2.imshow("filtro_img",filtro_img)
		#print(frame)
		if cv2.waitKey(100) == 97: # desactivar el video con la letra a del teclado
			break
	else:
		break
cap.release()
cv2.destroyAllWindows()

### Contornos en cámara de video de color rojo

In [5]:
import cv2
import numpy as np 

cap = cv2.VideoCapture(0)

Redlower1 = np.array([0,80,80], np.uint8)
Redupper1 = np.array([8,255,255], np.uint8)

Redlower2 = np.array([175,80,80], np.uint8)
Redupper2 = np.array([179,255,255], np.uint8)

while cap.isOpened():
	ret, frame = cap.read()
	frame_hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
	mascara1 = cv2.inRange(frame_hsv, Redlower1, Redupper1)
	mascara2 = cv2.inRange(frame_hsv, Redlower2, Redupper2)
	mascara = cv2.add(mascara1, mascara2)
	contours, hierarchy = cv2.findContours(mascara,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
	color = (0,255,0)
	cv2.drawContours(frame,contours,-1,color,2)
	#filtro_img = cv2.bitwise_and(frame,frame,mask = mascara)
	if ret == True:
		cv2.imshow("Video", frame)
		#cv2.imshow("mascara",mascara)
		#cv2.imshow("filtro_img",filtro_img)
		#print(frame)
		if cv2.waitKey(25) == 97: # desactivar el video con la letra a del teclado
			break
	else:
		break
cap.release()
cv2.destroyAllWindows()

### Contornos simples en geometrías que no requieren todos los puntos del contorno.

In [7]:
import cv2

image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_cuadrado.jpg")
image_GRAY = cv2.cvtColor(image_BGR,cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

ret,image_with_threshold = cv2.threshold(image_GRAY,valor_umbral,valor_maximo,tipo)
contours, hierarchy = cv2.findContours(image_with_threshold,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
print(contours[0])
color = (0,255,0)

for contour in contours[0]:
	contour = contour[0]
	start = (contour[0]-2,contour[1]-2)
	end = (contour[0]+7,contour[1]+7)
	cv2.rectangle(image_BGR,start,end,color,-1)


#cv2.drawContours(image_BGR,contours,-1,color,8)
cv2.imshow("imagen umbralizada",image_with_threshold)
cv2.imshow("imagen con contornos",image_BGR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

[[[ 90  90]]

 [[ 90 269]]

 [[269 269]]

 [[269  90]]]


## Momentos del contorno: área y perímetro. el área está en píxeles cuadrados

m00: área de la imagen

m10: centroide del eje x

m01: centroide del eje y

#m20 orientación

In [17]:
import cv2

'''
No olvidar que aquí se estima es el área del CONTORNO NO EL ÁREA DE LA IMAGEN. Además, el perímetro y el área están en unidades de píxeles, pero se pueden convertir a milímetros, etc.
'''



image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_cuadrado.jpg")
image_GRAY = cv2.cvtColor(image_BGR, cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

retval, image_with_threshold = cv2.threshold(image_GRAY, valor_umbral, valor_maximo,tipo)
print(f"umbral {retval} y la imagen umbralizada {image_with_threshold}")
contours, hierarchy = cv2.findContours(image_with_threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]
moments = cv2.moments(contour)
print("Momentos 00 (área): ", moments['m00'])

area = cv2.contourArea(contour)
print(f"Área {area}")

p = cv2.arcLength(contour, True)
print(f"Perímetro {p}")

umbral 127.0 y la imagen umbralizada [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Momentos 00 (área):  32041.0
Área 32041.0
Perímetro 716.0


## hallando el contorno normal de una imagen

In [21]:
image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_3.png")
image_GRAY = cv2.cvtColor(image_BGR, cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

retval, image_with_threshold = cv2.threshold(image_GRAY, valor_umbral, valor_maximo,tipo)
print(f"umbral {retval} y la imagen umbralizada {image_with_threshold}")
contours, hierarchy = cv2.findContours(image_with_threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]


color = (0,255,0)
cv2.drawContours(image_BGR, contours, -1, color, 2) # aquí van los contornos, - se grafican todos los contornos, y 2 es el grosor.



#cv2.drawContours(image_BGR,contours,-1,color,8)
cv2.imshow("imagen con contornos",image_BGR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

umbral 127.0 y la imagen umbralizada [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Obteniendo el la aproximación del contorno de una imagen

In [24]:
image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_3.png")
image_GRAY = cv2.cvtColor(image_BGR, cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

retval, image_with_threshold = cv2.threshold(image_GRAY, valor_umbral, valor_maximo,tipo)
print(f"umbral {retval} y la imagen umbralizada {image_with_threshold}")
contours, hierarchy = cv2.findContours(image_with_threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]

perimetro = cv2.arcLength(contour, True)
distancia = 0.09 * perimetro # si este parámetro es más bajo, alcanza a realizar la proximación del contorno

aprox_contour = cv2.approxPolyDP(contour, distancia, True)
print(f"Contorno aproximado{aprox_contour}")
print(f"Contorno: {contour}")


color = (0,255,0)
cv2.drawContours(image_BGR,[aprox_contours], -1, color, 2) ## se pone corchetes porque el parámetro


#cv2.drawContours(image_BGR,contours,-1,color,8)
cv2.imshow("imagen con contornos", image_BGR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

umbral 127.0 y la imagen umbralizada [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Contorno aproximado[[[ 51  35]]

 [[ 51 202]]

 [[421 202]]

 [[421  35]]]
Contorno: [[[ 51  35]]

 [[ 51 111]]

 [[ 53 109]]

 [[ 54 109]]

 [[ 55 108]]

 [[ 60 108]]

 [[ 61 107]]

 [[ 63 107]]

 [[ 66 104]]

 [[ 67 104]]

 [[ 68 103]]

 [[ 69 103]]

 [[ 70 102]]

 [[ 71 102]]

 [[ 81  92]]

 [[ 82  92]]

 [[ 84  90]]

 [[ 85  90]]

 [[ 86  89]]

 [[ 87  89]]

 [[ 88  88]]

 [[ 89  88]]

 [[ 91  86]]

 [[ 91  85]]

 [[ 92  84]]

 [[ 93  84]]

 [[ 94  83]]

 [[ 95  83]]

 [[ 97  81]]

 [[ 98  81]]

 [[100  79]]

 [[101  79]]

 [[103  77]]

 [[105  79]]

 [[105  82]]

 [[104  83]]

 [[102  83]]

 [[101  84]]

 [[100  84]]

 [[ 98  86]]

 [[ 97  86]]

 [[ 96  87]]

 [[ 95  87]]

 [[ 93  89]]

 [[ 93  90]]

 [[ 92  91]]

 [[ 91  91]]

 [[ 90  92]]

 [[ 89  92]]

 [[ 88  93]]

 [[ 87  93]]

 [[ 85  95]]

 [[ 84  95]]

 [[ 75 104]]

 [

## Envoltura convexa

In [15]:
image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_para_envoltura_convexa.png")
image_GRAY = cv2.cvtColor(image_BGR, cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

retval, image_with_threshold = cv2.threshold(image_GRAY, valor_umbral, valor_maximo,tipo)

contours, hierarchy = cv2.findContours(image_with_threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]
#Para saber si el contorno es convexo de la imagen:
is_convex_contour = cv2.isContourConvex(convex_Hull)
print(is_convex_contour)

perimetro = cv2.arcLength(contour, True)
distancia = 0.09 * perimetro # si este parámetro es más bajo, alcanza a realizar la proximación del contorno

#aprox_contour = cv2.approxPolyDP(contour, distancia, True)
convex_Hull = cv2.convexHull(contour, returnPoints = True) # se  pone returnpoints para que se obtengan las coordenadas. Para que devuelva contornos
color = (0,255,0)
cv2.drawContours(image_BGR, [convex_Hull], -1, color, 2) ## sin corchetes [] graficará los puntos de manera independiente. Pero con corchetes trabaja un único contorno completo. Por eso une los 4 puntos.
# es mucho más eficiente agregando los corcehtes en [convex_Hull] porque une los puntos de la envoltura


#cv2.drawContours(image_BGR,contours,-1,color,8)
cv2.imshow("imagen con contornos", image_BGR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

True


## Cuadro delimitador

In [16]:
import cv2

image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_para_cuadrodelimitador.png")
image_GRAY = cv2.cvtColor(image_BGR,cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

ret,image_with_threshold = cv2.threshold(image_GRAY,valor_umbral,valor_maximo,tipo)

contours, hierarchy = cv2.findContours(image_with_threshold,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
contour = contours[0]

x,y,w,h = cv2.boundingRect(contour) # w, h es el ancho y alto del cuadro delimitador. x, y son las puntos de la esquina superior izquierda. por tanto a partir de x, y se suma el ancho y el alto para delimitar 

color = (0,255,0)
cv2.rectangle(image_BGR,(x,y),(x+w,y+h),color,2)

cv2.imshow("imagen con contornos",image_BGR)
cv2.waitKey(100000)
cv2.destroyAllWindows()

## cuadro delimitador rotado (área mínima de contorno cuadrado)

In [24]:
import cv2

image_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_para_cuadrodelimitador2.png")
image_GRAY = cv2.cvtColor(image_BGR,cv2.COLOR_BGR2GRAY)

valor_maximo = 255
valor_umbral = 127
tipo = cv2.THRESH_BINARY

ret,image_with_threshold = cv2.threshold(image_GRAY,valor_umbral,valor_maximo,tipo)

contours, hierarchy = cv2.findContours(image_with_threshold,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
contour = contours[0]
(x,y), (w,h), angle = cv2.minAreaRect(contour) # coordendas del cuadro delimitador mínimo y ángulo del cuadro
box = cv2.boxPoints(((x,y), (w,h), angle))
box = np.int64(box)
print(box)

x,y,w,h = cv2.boundingRect(contour) # w, h es el ancho y alto del cuadro delimitador. x, y son las puntos de la esquina superior izquierda. por tanto a partir de x, y se suma el ancho y el alto para delimitar 

color = (0,255,0)
cv2.rectangle(image_BGR, (x,y), (x+w, y+h),color, 2)
cv2.drawContours(image_BGR, [box], -1, color, 2)

cv2.imshow("imagen con contornos",image_BGR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

[[ 74 117]
 [228  -2]
 [279  63]
 [125 183]]
