In [1]:
import cv2
import numpy as np

In [4]:
img = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagenrgb.png")

In [5]:
b,g,r = cv2.split(img) 

## Lo anterior es equivalente a lo siguiente, en manejo de tuplas y slicing
# b = img[:,:,0] # todas las filas, todas las columnas del plano 0 (azul)
# g = img[:,:,1] # todas las filas, todas las columnas del plano 0 (verde)
# r = img[:,:,2] # todas las filas, todas las columnas del plano 0 (rojo)

cv2.imshow("ventana",img)
cv2.imshow("ventana azul",b)
cv2.imshow("Ventana verde", g)
cv2.imshow("Ventana rojo", r)
cv2.waitKey(7000)
cv2.destroyAllWindows()

In [8]:
## Mostrando una sola banda
img[:,:,0] = 0 # anulando todas los pixeles del azul
img[:,:,1] = 0 # anulando todas los pixeles del verde

print(img, type(img))
cv2.imshow("ventana",img)
#cv2.imshow("ventana azul",b)
#cv2.imshow("Ventana verde", g)
#cv2.imshow("Ventana rojo", r)
cv2.waitKey(7000)
cv2.destroyAllWindows()


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>


In [9]:
img = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")


## Mostrando una sola banda
img[:,:,0] = 0 # anulando todas los pixeles del azul
img[:,:,1] = 0 # anulando todas los pixeles del verde
#img[:,:,2] = 0 # anulando todas los pixeles del verde

print(img, type(img), img.shape, img.dtype)
cv2.imshow("ventana",img)
#cv2.imshow("ventana azul",b)
#cv2.imshow("Ventana verde", g)
#cv2.imshow("Ventana rojo", r)
cv2.waitKey(7000)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'> (225, 225, 3) uint8


## Operaciones aritméticas bit a bit con AND (en AND el pixel menor manda)

In [7]:
help(cv2.bitwise_and)

Help on built-in function bitwise_and:

bitwise_and(...)
    bitwise_and(src1, src2[, dst[, mask]]) -> dst
    .   @brief computes bitwise conjunction of the two arrays (dst = src1 & src2)
    .   Calculates the per-element bit-wise conjunction of two arrays or an
    .   array and a scalar.
    .
    .   The function cv::bitwise_and calculates the per-element bit-wise logical conjunction for:
    .   *   Two arrays when src1 and src2 have the same size:
    .       \f[\texttt{dst} (I) =  \texttt{src1} (I)  \wedge \texttt{src2} (I) \quad \texttt{if mask} (I) \ne0\f]
    .   *   An array and a scalar when src2 is constructed from Scalar or has
    .       the same number of elements as `src1.channels()`:
    .       \f[\texttt{dst} (I) =  \texttt{src1} (I)  \wedge \texttt{src2} \quad \texttt{if mask} (I) \ne0\f]
    .   *   A scalar and an array when src1 is constructed from Scalar or has
    .       the same number of elements as `src2.channels()`:
    .       \f[\texttt{dst} (I) =  \t

#### Multiplicación de una sola banda de la imagen con otra imagen creada

In [16]:
## Se multiplica (AND) la imagen de mario que tiene 225, 225 pixeles por una imagen del mismo tamaño creada artificalmente. En este caso solo utilizamos una banda de la imagen, la del azul (0)
img_mario = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg", 0)
img_creada = np.zeros((225, 225), dtype = np.uint8)

cv2.circle(img_creada, (128, 128), 50, 255, -1)
AND = cv2.bitwise_and(img_creada, img_mario)

cv2.imshow("ventana", img_mario)
cv2.imshow("ventana img_ nueva", img_creada)
cv2.imshow("Imagen resultante", AND)
cv2.waitKey(7000)
cv2.destroyAllWindows()

#### Multiplicación de todas las bandas de la imagen con otra de una sola banda. Esto se conoce como máscara

In [20]:
## Se multiplica (AND) la imagen de mario que tiene 225, 225 pixeles por una imagen del mismo tamaño creada artificalmente. En este caso solo utilizamos una banda de la imagen, la del azul (0)
img_mario = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")
img_creada = np.zeros((225, 225), dtype = np.uint8)

cv2.circle(img_creada, (128, 128), 50, 255, -1)
AND = cv2.bitwise_and(img_mario, img_mario, mask = img_creada)

cv2.imshow("ventana", img_mario)
cv2.imshow("ventana img_ nueva", img_creada)
cv2.imshow("Imagen resultante", AND)
cv2.waitKey(7000)
cv2.destroyAllWindows()

#### Otra forma

In [30]:
## Se multiplica (AND) la imagen de mario que tiene 225, 225 pixeles por una imagen del mismo tamaño creada artificalmente. En este caso solo utilizamos una banda de la imagen, la del azul (0)
img_mario = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")
img_creada = np.zeros((225, 225, 3), dtype = np.uint8)

cv2.circle(img_creada, (128, 128), 50, (255, 255, 255), -1)
AND = cv2.bitwise_and(img_creada, img_mario)

cv2.imshow("ventana", img_mario)
cv2.imshow("ventana img_ nueva", img_creada)
cv2.imshow("Imagen resultante", AND)
cv2.waitKey(7000)
cv2.destroyAllWindows()

## Operaciones aritméticas bit a bit con OR (el mayor valor manda)

In [32]:
img_mario = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg", 0)
img_creada = np.zeros((225, 225), dtype = np.uint8)

cv2.circle(img_creada, (128, 128), 50, 255, -1)
OR= cv2.bitwise_or(img_mario, img_creada)

cv2.imshow("ventana", img_mario)
cv2.imshow("ventana img_ nueva", img_creada)
cv2.imshow("Imagen resultante", OR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

#### Utilizando las tres bandas

In [35]:
img_mario = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")
img_creada = np.zeros((225, 225, 3), dtype = np.uint8)

cv2.circle(img_creada, (128, 128), 50, (255, 255, 255), -1)
OR= cv2.bitwise_or(img_mario, img_creada)

cv2.imshow("ventana", img_mario)
cv2.imshow("ventana img_ nueva", img_creada)
cv2.imshow("Imagen resultante", OR)
cv2.waitKey(10000)
cv2.destroyAllWindows()

## Operaciones aritméticas bit a bit con NOT

In [40]:
img_mario = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")
img_creada = np.zeros((225, 225, 3), dtype = np.uint8)

cv2.circle(img_creada, (128, 128), 50, (255, 255, 255), -1)
OR = cv2.bitwise_or(img_mario, img_creada)
NOT = cv2.bitwise_not(img_creada)

cv2.imshow("ventana", img_mario)
cv2.imshow("ventana img_ nueva", img_creada)
cv2.imshow("Imagen resultante", OR)
cv2.imshow('Imagen not', NOT)
cv2.waitKey(15000)
cv2.destroyAllWindows()