In [1]:
import numpy as np
import cv2
import os

In [2]:
os.getcwd()

'C:\\jupyter\\pdi'

In [3]:
img = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\satelite.jpg")

In [6]:
## Leyendo una imagen. imshow muestra la imagen en un pesatañeo, por eso se agrega witkey que espera en segundos antes de cerrarse la ventana emergente, en conjunto con destroyAllWindows
cv2.imshow('Ventana', img)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

In [7]:
## Para guardar una imagen
cv2.imshow('Ventana', img)
if cv2.waitKey(0) == 97:
    cv2.imwrite("C:\\Jupyter\\pdi\\imagenes\\satelite2.jpg", img)
cv2.destroyAllWindows()

In [8]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



### Creando una matriz y creando una imagen con todos los pixeles en 0, es decir negro

In [12]:
z = np.zeros((400, 400), dtype = np.uint8)  # filas y columnas

In [13]:
## Mostrando la imagen. Como se creó una matriz de ceros, entonces los pixeles son negros
cv2.imshow('Ventana', z)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

### Creando una matriz de pixeles en gris, adicionando 125

In [12]:
z = np.zeros((400, 400), dtype = np.uint8)  # filas y columnas

In [13]:
## Mostrando la imagen. Como se creó una matriz de ceros, entonces los pixeles son negros
cv2.imshow('Ventana', z)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

### Funciones de dibujo - Línea

In [14]:
z = np.zeros((400, 400), dtype = np.uint8) 

In [15]:
cv2.line(z, (10, 10), (350, 350), 125) ## se ponen 2 puntos de x,y. Siendo  porque esta imagen solo tiene un canal. y 125 es el colo de la línea. X -es columna, y -filas

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [16]:
## Mostrando la imagen. Como se creó una matriz de ceros, entonces los pixeles son negros
cv2.imshow('Ventana', z)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

In [23]:
## Línea vertical con 3 canales (400, 400, 3)

z = np.zeros((400, 400, 3), dtype = np.uint8) ## dimensiones de x,y,z
cv2.line(z, (200, 0), (200, 399), (0, 0, 255), 4) #200 es x = columna; 0 es y, que es igual a fila

## Mostrando la imagen. Como se creó una matriz de ceros, entonces los pixeles son negros
cv2.imshow('Ventana', z)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

In [24]:
## Línea horizontal con 3 canales (400, 400, 3)

z = np.zeros((400, 400, 3), dtype = np.uint8) ## dimensiones de x,y,z
cv2.line(z, (0, 200), (399, 200), (0, 0, 255), 4) #0 es x = columna; 200 es y, que es igual a fila

## Mostrando la imagen. Como se creó una matriz de ceros, entonces los pixeles son negros
cv2.imshow('Ventana', z)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

### Dibujando rectángulos

In [44]:
z = np.zeros((400, 400, 3), dtype = np.uint8) ## dimensiones de x,y,z
cv2.rectangle(z, (50, 50), (350, 350), (0,255, 0), 4) # la primera coordenada es la superior izquierda (50, 50) y la segunda (350, 350) es la inferior derecha

## Mostrando la imagen. Como se creó una matriz de ceros, entonces los pixeles son negros
cv2.imshow('Ventana', z)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

### Analizando la matriz para la imagen 

In [32]:
## Leyendo una imagen. imshow muestra la imagen en un pesatañeo, por eso se agrega witkey que espera en segundos antes de cerrarse la ventana emergente, en conjunto con destroyAllWindows
img = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\satelite.jpg", 0) # - 1 para conservar transparencia en una imagen; 0 para  leer la imagen en escala de gris; 1 es 
print(img, type(img), img.ndim, img.shape, img.dtype) # img.dtype muestra el rango de valores que toma cada pixel; ndim = número de canales; 
cv2.imshow('Ventana', img)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

[[ 20  20  20 ...  20  20  22]
 [ 20  20  20 ...  19  18  19]
 [ 20  20  20 ...  19  20  22]
 ...
 [191 181 185 ...  39  40  41]
 [188 185 191 ...  35  37  40]
 [187 153 150 ...  34  31  30]] <class 'numpy.ndarray'> 2 (1280, 1920) uint8


In [35]:
## leyendo la imagen en escala de grises, ya no los tres canales, en la función de imread, sería el valor de 0
## Leyendo una imagen. imshow muestra la imagen en un pesatañeo, por eso se agrega witkey que espera en segundos antes de cerrarse la ventana emergente, en conjunto con destroyAllWindows
print(img, type(img), img.ndim, img.shape, img.dtype) # img.dtype muestra el rango de valores que toma cada pixel; ndim = número de canales; 
cv2.imshow('Ventana', img)
cv2.waitKey(5000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

[[ 20  20  20 ...  20  20  22]
 [ 20  20  20 ...  19  18  19]
 [ 20  20  20 ...  19  20  22]
 ...
 [191 181 185 ...  39  40  41]
 [188 185 191 ...  35  37  40]
 [187 153 150 ...  34  31  30]] <class 'numpy.ndarray'> 2 (1280, 1920) uint8


### Adicionando un rectángulo a uma imagen

In [47]:
## Leyendo una imagen. imshow muestra la imagen en un pesatañeo, por eso se agrega witkey que espera en segundos antes de cerrarse la ventana emergente, en conjunto con destroyAllWindows
img = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")
print(img, type(img), img.ndim, img.shape, img.dtype) # img.dtype muestra el rango de valores que toma cada pixel; ndim = número de canales; 
cv2.rectangle(img, (23, 27), (195, 202), (0,255, 0)) #envuelve la cara de mario
cv2.imshow('Ventana', img)
cv2.waitKey(10000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

[[[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 ...

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]] <class 'numpy.ndarray'> 3 (225, 225, 3) uint8


### Adicionando un círculo a uma imagen

In [7]:
## Leyendo una imagen. imshow muestra la imagen en un pesatañeo, por eso se agrega witkey que espera en segundos antes de cerrarse la ventana emergente, en conjunto con destroyAllWindows
img = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\mario.jpg")
print(img, type(img), img.ndim, img.shape, img.dtype) # img.dtype muestra el rango de valores que toma cada pixel; ndim = número de canales; 
cv2.rectangle(img, (23, 27), (195, 202), (0,255, 0)) #envuelve la cara de mario
cv2.circle(img, (110, 146), 80, (255, 0, 255), 5) ## 100 radio; (255, 0, 255) magenta; 5 es grosor
cv2.imshow('Ventana', img)
cv2.waitKey(10000) ## 5000 son 5 segundos. Es el tiempo que se mostrará la imagen
cv2.destroyAllWindows()

[[[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 ...

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]

 [[173  96   0]
  [173  96   0]
  [173  96   0]
  ...
  [173  96   0]
  [173  96   0]
  [173  96   0]]] <class 'numpy.ndarray'> 3 (225, 225, 3) uint8


### Dibujando un círculo relleno, un rectángulo relleno

In [17]:
bandera = np.zeros((400, 800, 3), dtype = np.uint8)
cv2.rectangle(bandera, (50, 50), (720, 350), (255, 255, 255), -1)
cv2.circle(bandera, (383, 198), 100, (0, 0, 255), -1)
cv2.imshow("Ventana", bandera)
cv2.waitKey(10000)
cv2.destroyAllWindows()

### Adicionando texto

In [26]:
# help(cv2.putText)
bandera = np.zeros((400, 800, 3), dtype = np.uint8)
cv2.rectangle(bandera, (50, 50), (720, 350), (255, 255, 255), -1)
cv2.circle(bandera, (383, 198), 100, (0, 0, 255), -1)
cv2.putText(bandera, "Japón", (280, 375), cv2.FONT_ITALIC, 1, (0, 255, 0))
cv2.imshow("Ventana", bandera)
cv2.waitKey(10000)
cv2.destroyAllWindows()