In [2]:
import numpy as np
import cv2

## Transformación morfológica - erosión

In [7]:
matrix = np.zeros((10,10), dtype = np.uint8)
matrix[:, 3:7] = 255


kernel = np.ones((3,3), dtype = np.uint8)
erosion = cv2.erode(matrix, kernel)
print("matriz 1")
print(matrix)
print("matriz 2")
print(erosion)

matriz 1
[[  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]]
matriz 2
[[  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]]


In [3]:
image_as_bgr = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\imagen_para_erosionar.png")
image_as_gray = cv2.cvtColor(image_as_bgr, cv2.COLOR_BGR2GRAY)

kernel = np.ones((3,3), dtype = np.uint8)
erosion = cv2.erode(image_as_gray, kernel, iterations = 2) ## significa que aplica la erosión 2 veces en la imagen

cv2.imshow("Imagen original", image_as_gray)
cv2.imshow("Imagen erosionada", erosion)
cv2.waitKey(15000)
cv2.destroyAllWindows()