In [7]:
import cv2
import numpy as np

In [2]:
imagen_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\sudoku.jpg")
imagen_GRAY = cv2.cvtColor(imagen_BGR, cv2.COLOR_BGR2GRAY)

In [14]:
imagen_BGR.shape

(423, 419, 3)

In [3]:
valor_umbral_min = 50
valor_umbral_max = 100
tamaño_kernel = 3

In [4]:
imagen_con_canny = cv2.Canny(imagen_GRAY, valor_umbral_min, valor_umbral_max, apertureSize = tamaño_kernel)

In [8]:
valor_umbral = 175 # si hay pixeles donde han pasado más de 175 líneas, crea una línea
lineas = cv2.HoughLines(imagen_con_canny, rho = 1, theta = np.pi/180, threshold = valor_umbral)

In [21]:
for index in range(len(lineas)):
    rho = lineas[index][0][0]
    theta = lineas[index][0][1]

    a = np.cos(theta)
    b = np.sin(theta)

    x_0 = a * rho
    y_0 = b * rho
    
    x_1 = int(x_0 + 500*(-b))
    y_1 = int(y_0 + 500*(a))

    x_2 = int(x_0 - 500*(-b))
    y_2 = int(y_0 - 500*(a))
    
    
    #Con las coordenadas se puede trazar la línea
    cv2.line(imagen_BGR, (x_1, y_1), (x_2, y_2), (0, 255, 0), 2)

cv2.imshow("Imagen original", imagen_BGR)
cv2.imshow("Imagen con Cannyl", imagen_con_canny)
cv2.waitKey(15000)
cv2.destroyAllWindows()

### Otro ejemplo

In [29]:
imagen_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\linea.png")
imagen_GRAY = cv2.cvtColor(imagen_BGR, cv2.COLOR_BGR2GRAY)

valor_umbral_min = 50
valor_umbral_max = 100
tamaño_kernel = 3

imagen_con_canny = cv2.Canny(imagen_GRAY, valor_umbral_min, valor_umbral_max, apertureSize = tamaño_kernel)
valor_umbral = 50 # si hay pixeles donde han pasado más de 175 líneas, crea una línea
lineas = cv2.HoughLines(imagen_con_canny, rho = 1, theta = np.pi/180, threshold = valor_umbral)

for index in range(len(lineas)):
    rho = lineas[index][0][0]
    theta = lineas[index][0][1]

    a = np.cos(theta)
    b = np.sin(theta)

    x_0 = a * rho
    y_0 = b * rho
    
    x_1 = int(x_0 + 500*(-b))
    y_1 = int(y_0 + 500*(a))

    x_2 = int(x_0 - 500*(-b))
    y_2 = int(y_0 - 500*(a))
    
    
    #Con las coordenadas se puede trazar la línea
    cv2.line(imagen_BGR, (x_1, y_1), (x_2, y_2), (0, 255, 0), 2)

cv2.imshow("Imagen original", imagen_BGR)
cv2.imshow("Imagen con Cannyl", imagen_con_canny)
cv2.waitKey(15000)
cv2.destroyAllWindows()

### Trasnformada de Hough probabilística

In [28]:
imagen_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\sudoku.jpg")
imagen_GRAY = cv2.cvtColor(imagen_BGR, cv2.COLOR_BGR2GRAY)

valor_umbral_min = 50
valor_umbral_max = 100
tamaño_kernel = 3
imagen_con_canny = cv2.Canny(imagen_GRAY, valor_umbral_min, valor_umbral_max, apertureSize = tamaño_kernel)

valor_umbral = 80 # si hay pixeles donde han pasado más de 175 líneas, crea una línea

## Obteniendo las líneas a partir del método porbabilístico de la transformada de hough -> HouhgLinesP
lineas = cv2.HoughLinesP(imagen_con_canny, rho = 1, theta = np.pi/180, threshold = valor_umbral, minLineLength = 100, maxLineGap = 15)
print(lineas)

for index in range(len(lineas)):
    x_1, y_1, x_2, y_2 = lineas[index][0]
    cv2.line(imagen_BGR, (x_1, y_1), (x_2, y_2), (0, 255, 0), 2)
    


cv2.imshow("Imagen original", imagen_BGR)
cv2.imshow("Imagen con Cannyl", imagen_con_canny)
cv2.waitKey(15000)
cv2.destroyAllWindows()


[[[ 36 271 347 271]]

 [[ 36 268 339 268]]

 [[294   2 307 391]]

 [[148 325 152 202]]

 [[185 412 188 253]]

 [[188 410 193  94]]

 [[ 27 406  38 278]]

 [[226 390 226   1]]

 [[149 389 162   0]]

 [[299  83 306 311]]

 [[260   5 263 229]]

 [[228 390 228 154]]

 [[266 199 269 391]]

 [[ 45 159 209 159]]

 [[379  13 404 367]]

 [[107 407 125  62]]

 [[ 25 386  58   6]]

 [[336 157 348 392]]

 [[330   4 350 392]]

 [[107 356 123  62]]

 [[ 44 162 260 162]]

 [[ 51 127 154 127]]

 [[ 51 129 157 129]]

 [[385  13 409 368]]

 [[ 20 403 192 406]]

 [[374   0 397 335]]

 [[372 153 388 392]]

 [[ 54  94 248  97]]

 [[218 348 388 348]]

 [[283 391 390 392]]

 [[ 98 234 301 234]]

 [[365   1 388 337]]

 [[ 81 195 266 195]]

 [[ 41 197 222 197]]

 [[370   2 393 337]]

 [[ 42 231 166 231]]

 [[ 66 407  86 117]]

 [[ 81 157  91  26]]

 [[375 152 391 391]]

 [[199   9 368   0]]

 [[ 59 309 209 309]]

 [[ 90 307 237 307]]

 [[190 310 365 310]]

 [[257   7 368   3]]

 [[221 308 355 308]]

 [[191  45

In [36]:
imagen_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\linea.png")
imagen_GRAY = cv2.cvtColor(imagen_BGR, cv2.COLOR_BGR2GRAY)

valor_umbral_min = 50
valor_umbral_max = 100
tamaño_kernel = 3
imagen_con_canny = cv2.Canny(imagen_GRAY, valor_umbral_min, valor_umbral_max, apertureSize = tamaño_kernel)

valor_umbral = 45 # si hay pixeles donde han pasado más de 175 líneas, crea una línea

## Obteniendo las líneas a partir del método porbabilístico de la transformada de hough -> HouhgLinesP
lineas = cv2.HoughLinesP(imagen_con_canny, rho = 1, theta = np.pi/180, threshold = valor_umbral, minLineLength = 100, maxLineGap = 15)
print(lineas)

for index in range(len(lineas)):
    x_1, y_1, x_2, y_2 = lineas[index][0]
    cv2.line(imagen_BGR, (x_1, y_1), (x_2, y_2), (0, 255, 0), 2)
    


cv2.imshow("Imagen original", imagen_BGR)
cv2.imshow("Imagen con Cannyl", imagen_con_canny)
cv2.waitKey(15000)
cv2.destroyAllWindows()

[[[373 179 373   0]]

 [[ 86 114 201  39]]

 [[ 92 117 203  43]]

 [[154 130 257 159]]

 [[156 125 257 154]]]


## Aplicando la trasnformada de Hough para imágenes con objetos circulares

In [45]:
imagen_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\linea.png")
imagen_GRAY = cv2.cvtColor(imagen_BGR, cv2.COLOR_BGR2GRAY)

imagen_con_Blur = cv2.medianBlur(imagen_GRAY, 3)


## Obteniendo las líneas a partir del método porbabilístico de la transformada de hough -> HouhgLinesP
circulos = cv2.HoughCircles(imagen_con_Blur,cv2.HOUGH_GRADIENT, 3, 110, param1 = 150, param2 = 100, minRadius = 30, maxRadius = 150)
print(circulos)

for values in circulos[0,:]:
    print(values[0],values[1],values[2])
    cv2.circle(imagen_BGR,(int(values[0]),int(values[1])),int(values[2]),(0,255,0),2)


cv2.imshow("Imagen con blur", imagen_con_Blur)
cv2.imshow("Imagen BGR", imagen_BGR)
cv2.waitKey(15000)
cv2.destroyAllWindows()


None


TypeError: 'NoneType' object is not subscriptable

In [46]:
import cv2
import numpy as np

image_as_BGR = cv2.imread("C:\\Jupyter\\pdi\\imagenes\\linea.png")
image_as_GRAY = cv2.cvtColor(image_as_BGR,cv2.COLOR_BGR2GRAY)

image_with_Blur = cv2.medianBlur(image_as_GRAY,3)

circles = cv2.HoughCircles(image_with_Blur,cv2.HOUGH_GRADIENT, 3, 110, param1 = 150, param2 = 100, minRadius = 30, maxRadius = 150)

for values in circles[0,:]:
    print(values[0],values[1],values[2])
    cv2.circle(image_as_BGR,(int(values[0]),int(values[1])),int(values[2]),(0,255,0),2)


cv2.imshow("Imagen",image_with_Blur)
cv2.imshow("Imagen con canny",image_as_BGR)
cv2.waitKey()
cv2.destroyAllWindows()

TypeError: 'NoneType' object is not subscriptable